cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: #access key
      secret-key: #secret key

    sqs:
      url: https://sqs.us-east-2.amazonaws.com/320241143100/SimpleSendingMessageQueue
      name: SimpleSendingMessageQueue
